const fs = require('fs');
const path = require('path');

// Build a fully static Docsify site with embedded content
function buildStatic() {
  const docsDir = __dirname;
  const outputFile = path.join(docsDir, 'index.html');

  // Read all markdown files
  const files = {};

  fs.readdirSync(docsDir).forEach(file => {
    if (file.endsWith('.md') && file !== '_sidebar.md') {
      const content = fs.readFileSync(path.join(docsDir, file), 'utf8');
      files[file] = content;
    }
  });

  // Build search index
  const searchIndex = buildSearchIndex(files);

  // Generate static HTML
  const html = generateStaticHTML(files, searchIndex);

  fs.writeFileSync(outputFile, html, 'utf8');

  console.log('✅ Static documentation generated:', outputFile);
  console.log(`📄 ${Object.keys(files).length} markdown files embedded`);
  console.log(`🔍 ${searchIndex.length} search index entries`);
}

function extractTitle(content) {
  const match = content.match(/^#\s+(.+)$/m);
  return match ? match[1].trim() : 'Untitled';
}

function buildSearchIndex(files) {
  const index = [];

  Object.entries(files).forEach(([fileName, content]) => {
    const lines = content.split('\n');
    let currentSection = extractTitle(content);

    lines.forEach(line => {
      const trimmed = line.trim();

      // Skip code blocks
      if (trimmed.startsWith('```')) return;

      // Extract headings
      const h1 = trimmed.match(/^#\s+(.+)$/);
      const h2 = trimmed.match(/^##\s+(.+)$/);
      const h3 = trimmed.match(/^###\s+(.+)$/);

      if (h1) {
        currentSection = h1[1];
        index.push({
          title: currentSection,
          heading: currentSection,
          text: trimmed,
          url: `#/${fileName}`,
          level: 1
        });
      } else if (h2) {
        const heading = h2[1];
        index.push({
          title: `${currentSection} - ${heading}`,
          heading: heading,
          text: trimmed,
          url: `#/${fileName}?id=${slugify(heading)}`,
          level: 2
        });
      } else if (h3) {
        const heading = h3[1];
        index.push({
          title: `${currentSection} - ${heading}`,
          heading: heading,
          text: trimmed,
          url: `#/${fileName}?id=${slugify(heading)}`,
          level: 3
        });
      } else if (trimmed.length > 10 && !trimmed.startsWith('|') && !trimmed.startsWith('-')) {
        // Index content (skip tables and short lines)
        const words = trimmed.toLowerCase().split(/\s+/).filter(w => w.length > 3);
        if (words.length > 0) {
          index.push({
            title: currentSection,
            heading: currentSection,
            text: trimmed.substring(0, 150),
            url: `#/${fileName}`,
            level: 0
          });
        }
      }
    });
  });

  return index;
}

function slugify(text) {
  return text.toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

function generateSidebar(content) {
  const lines = content.split('\n');
  const sidebar = [];

  lines.forEach(line => {
    const h1 = line.match(/^#\s+(.+)$/);
    const h2 = line.match(/^##\s+(.+)$/);
    const h3 = line.match(/^###\s+(.+)$/);

    if (h1) {
      sidebar.push(`* [${h1[1]}](#${slugify(h1[1])})`);
    } else if (h2) {
      sidebar.push(`  * [${h2[1]}](#${slugify(h2[1])})`);
    } else if (h3) {
      sidebar.push(`    * [${h3[1]}](#${slugify(h3[1])})`);
    }
  });

  return sidebar.join('\n');
}

function generateStaticHTML(files, searchIndex) {
  const fileNames = Object.keys(files);
  const firstFile = 'So_tay_SA_VN.md';

  // Generate sidebar from main content
  const sidebarContent = generateSidebar(files[firstFile] || '');
  const sidebarEscaped = sidebarContent
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\${/g, '\\${');

  // Escape content for embedding in JavaScript
  const filesJS = Object.entries(files).map(([name, content]) => {
    const escaped = content
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\${/g, '\\${');
    return `'${name}': \`${escaped}\``;
  }).join(',\n      ');

  return `<!--
  ⚠️ DO NOT EDIT THIS FILE ⚠️
  This file is auto-generated by build-static.js
  To make changes, edit the source markdown files and run: node build-static.js
  Generated: ${new Date().toISOString()}
-->
<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sổ tay Solution Architect</title>
  <meta name="description" content="Tài liệu cho dev muốn hiểu SA làm gì, hoặc dev đang chuyển sang làm SA.">
  <link rel="icon" href="data:,">

  <!-- Google Fonts: Lexend Deca & JetBrains Mono -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css">

  <style>
    :root {
      --theme-color: #3F51B5;
      --theme-color-dark: #303F9F;
    }

    * {
      font-family: 'Lexend Deca', -apple-system, BlinkMacSystemFont, sans-serif !important;
    }

    body {
      font-family: 'Lexend Deca', -apple-system, BlinkMacSystemFont, sans-serif !important;
      font-weight: 400;
    }

    /* Sidebar */
    .sidebar {
      width: 280px !important;
      background: #fafafa;
      border-right: 1px solid #eee;
    }

    .sidebar-nav {
      padding: 20px 10px !important;
    }

    .sidebar-nav li {
      margin: 4px 0;
    }

    .sidebar-nav a {
      color: #000 !important;
      font-size: 0.9em;
      padding: 4px 8px;
      display: block;
      border-radius: 4px;
    }

    .sidebar-nav a:hover {
      background: #e8e8e8;
    }

    .sidebar-nav a.active {
      background: var(--theme-color);
      color: #fff !important;
    }

    .sidebar-toggle {
      display: none;
    }

    @media (max-width: 768px) {
      .sidebar {
        width: 100% !important;
      }
    }

    /* Main content */
    .content {
      left: 280px !important;
      right: 0 !important;
      padding: 30px 40px !important;
      max-width: none !important;
    }

    .markdown-section {
      max-width: 100% !important;
    }

    /* Headers */
    .markdown-section h1 {
      font-family: 'Lexend Deca', sans-serif !important;
      font-weight: 600;
      color: #000000;
      border-bottom: 2px solid var(--theme-color);
      padding-bottom: 0.3em;
      font-size: 2em;
    }

    .markdown-section h2 {
      font-family: 'Lexend Deca', sans-serif !important;
      font-weight: 600;
      color: #000;
      border-bottom: 1px solid #eee;
      padding-bottom: 0.2em;
      margin-top: 2em;
      font-size: 1.6em;
    }

    .markdown-section h3 {
      font-family: 'Lexend Deca', sans-serif !important;
      font-weight: 500;
      color: #000;
      margin-top: 1.5em;
      font-size: 1.3em;
    }

    .markdown-section h4,
    .markdown-section h5,
    .markdown-section h6 {
      font-family: 'Lexend Deca', sans-serif !important;
      font-weight: 500;
    }

    .markdown-section p,
    .markdown-section li,
    .markdown-section td,
    .markdown-section th,
    .markdown-section blockquote {
      font-family: 'Lexend Deca', sans-serif !important;
      font-weight: 400;
      line-height: 1.7;
      color: #000000;
    }

    /* Code - JetBrains Mono */
    code,
    pre,
    .token,
    .markdown-section code,
    .markdown-section pre,
    .markdown-section pre code {
      font-family: 'JetBrains Mono', 'Consolas', monospace !important;
    }

    .markdown-section code {
      background: #f3f4f6;
      color: #000;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 0.9em;
    }

    .markdown-section pre {
      background: #f8f9fa;
      border: 1px solid #e0e0e0;
      border-left: 4px solid var(--theme-color);
      border-radius: 6px;
      padding: 1rem;
      overflow-x: auto;
    }

    .markdown-section pre code {
      background: transparent;
      color: #000;
      padding: 0;
      font-size: 0.9em;
      line-height: 1.6;
    }

    /* Tables */
    .markdown-section table {
      width: auto;
      border-collapse: collapse;
      margin: 1rem 0;
      display: table;
    }

    .markdown-section th,
    .markdown-section td {
      padding: 8px 12px;
      border: 1px solid #ddd;
      text-align: left;
    }

    .markdown-section th {
      background: #f5f5f5;
      font-weight: 600;
      color: #000;
    }

    .markdown-section tr:nth-child(even) {
      background: #fafafa;
    }

    .markdown-section tr:hover {
      background: #f0f0f0;
    }

    /* Blockquote */
    .markdown-section blockquote {
      border-left: 4px solid var(--theme-color);
      background: rgba(63, 81, 181, 0.05);
      padding: 1rem 1.5rem;
      margin: 1.5rem 0;
      border-radius: 4px;
    }

    /* Links */
    .markdown-section a {
      color: var(--theme-color);
      text-decoration: none;
    }

    .markdown-section a:hover {
      text-decoration: underline;
    }

    /* HR */
    .markdown-section hr {
      border: none;
      border-top: 1px solid #e5e7eb;
      margin: 2em 0;
    }

    /* Lists */
    .markdown-section ul,
    .markdown-section ol {
      padding-left: 1.5em;
    }

    .markdown-section li {
      margin: 0.3em 0;
    }
  </style>
</head>
<body>
  <div id="app">Loading...</div>

  <script>
    // Embedded markdown content
    window.__staticDocs = {
      ${filesJS}
    };

    // Embedded sidebar
    window.__staticSidebar = \`${sidebarEscaped}\`;

    // Pre-generated search index
    window.__staticSearchIndex = ${JSON.stringify(searchIndex)};

    // Configure Docsify
    window.$docsify = {
      name: 'Sổ tay SA',
      repo: '',
      loadSidebar: true,
      loadNavbar: false,
      homepage: '${firstFile}',
      auto2top: true,
      maxLevel: 4,
      subMaxLevel: 3,
      coverpage: false,
      notFoundPage: true,
      themeColor: '#3F51B5',
      search: {
        maxAge: 86400000,
        paths: 'auto',
        placeholder: 'Tìm kiếm...',
        noData: 'Không tìm thấy kết quả',
        depth: 6
      },
      plugins: [
        function(hook, vm) {
          // Override fetch to serve from embedded content
          const originalFetch = window.fetch;
          window.fetch = function(url, options) {
            if (typeof url === 'string') {
              // Handle sidebar
              if (url.includes('_sidebar.md')) {
                return Promise.resolve(new Response(
                  window.__staticSidebar,
                  { headers: { 'Content-Type': 'text/markdown; charset=utf-8' } }
                ));
              }
              // Handle markdown files
              if (url.endsWith('.md') || url.includes('.md')) {
                const fileName = url.split('/').pop().split('?')[0];
                if (window.__staticDocs[fileName]) {
                  return Promise.resolve(new Response(
                    window.__staticDocs[fileName],
                    { headers: { 'Content-Type': 'text/markdown; charset=utf-8' } }
                  ));
                }
              }
            }
            return originalFetch.apply(this, arguments);
          };
        }
      ]
    };
  </script>

  <!-- Docsify core -->
  <script src="https://cdn.jsdelivr.net/npm/docsify@4"></script>

  <!-- Search plugin -->
  <script src="https://cdn.jsdelivr.net/npm/docsify/lib/plugins/search.min.js"></script>

  <!-- Syntax highlighting -->
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-bash.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-python.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-javascript.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-json.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-yaml.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-sql.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-go.min.js"></script>

  <!-- Mermaid diagrams -->
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <script>
    mermaid.initialize({
      startOnLoad: false,
      theme: 'default',
      securityLevel: 'loose'
    });

    // Render mermaid after docsify loads content
    function renderMermaid() {
      var selectors = [
        'pre[data-lang="mermaid"]',
        'code.language-mermaid',
        'code.lang-mermaid',
        '.language-mermaid'
      ];

      document.querySelectorAll(selectors.join(', ')).forEach(function(el) {
        if (el.closest('.mermaid')) return; // Already processed

        var code = el.textContent || el.innerText;
        var pre = el.tagName === 'CODE' ? el.parentElement : el;

        if (pre && pre.parentNode) {
          var div = document.createElement('div');
          div.className = 'mermaid';
          div.textContent = code;
          pre.parentNode.replaceChild(div, pre);
        }
      });

      try {
        mermaid.run();
      } catch(e) {
        console.error('Mermaid error:', e);
      }
    }

    // Hook into docsify
    if (window.$docsify) {
      window.$docsify.plugins = window.$docsify.plugins || [];
      window.$docsify.plugins.push(function(hook) {
        hook.doneEach(function() {
          setTimeout(renderMermaid, 100);
        });
      });
    }
  </script>
</body>
</html>`;
}

// Run builder
buildStatic();
